### ISSUE TITLE
Auto complete text destroys dark theme 

### ISSUE THREAD

**Issue by ryanrampage1** [SpartaHack/SpartaHack-Website#108]
Chrome on  osx or whatever its called version sierra 

<img width="636" alt="screen shot 2016-11-01 at 11 07 47 pm" src="https://cloud.githubusercontent.com/assets/7875323/19915425/84f76eae-a088-11e6-91bb-2caa5759e2d8.png">

<img width="584" alt="screen shot 2016-11-01 at 11 07 35 pm" src="https://cloud.githubusercontent.com/assets/7875323/19915424/84f6015e-a088-11e6-9a04-2e8d8661e3c8.png">

**Comment by bogdanpozderca** [comment]
fixed
