### ISSUE TITLE
"Who can come to SpartaHack" text is inaccurate

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack-Website#118]
![screenshot](https://cloud.githubusercontent.com/assets/1198161/19918937/be94cce8-a0a5-11e6-86ab-efb5b6a0e539.png)

MLH's FAQ says anyone who graduated within 12 months is eligible to go to member events: https://mlh.io/faq#i-just-graduated-can-i-still-come-to-an-event

maybe change the first sentence to "Anyone who is currently a student or has graduated within 12 months of SpartaHack!"

**Comment by bogdanpozderca** [comment]
fixed
