### ISSUE TITLE
"edit application" doesn't work

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack-Website#149]
submit button takes you to the "create account" page ![screenshot](https://cloud.githubusercontent.com/assets/1198161/19939872/08062eca-a101-11e6-9938-d6d6f071850a.png)

**Comment by mhammerly** [comment]
it also doesn't pre-populate the form at all haha

**Comment by milesjos** [comment]
Resolved at some point by Bogdan
