### ISSUE TITLE
After creating account and logging in, "Greetings, Nathan" Flickering cursor next to it

### ISSUE THREAD

**Issue by nathankurt** [SpartaHack/SpartaHack-Website#150]
Flickering Cursor next to name after logging in
![cursor problem](https://cloud.githubusercontent.com/assets/9864281/19939870/05784fd0-a101-11e6-90b9-91efc281fd41.png)

**Comment by nathankurt** [comment]
same thing for both light and dark theme on Chrome

**Comment by mhammerly** [comment]
i think it's an intentional visual effect
