### ISSUE TITLE
Editing app: make "Other College/University" required if "College/University not listed" checked

### ISSUE THREAD

**Issue by laurenbretz** [SpartaHack/SpartaHack-Website#166]
There should be an **asterisk next to "Other College/University" in both creating and editing** application since it is a required field if you check the box "College/University not listed".

When creating an application, the client side validation prompts you to fill in Other College/University if checkbox checked (even though no asterisk), but there is not client side validation on editing the application, so it fails silently if you change from a drop-down university to the university-not-listed checkbox.

**Comment by mhammerly** [comment]
the server/API validation checks to see if EITHER the normal `university` question is filled out OR the `other university` question is filled out, without respect to the `college/university not listed` checkbox. the checkbox needs to be sent to the server (if it isn't already) and used to unset the irrelevant university field and then if neither field is checked raise a validation error.

the client-side validation checks for `university || (not listed checkbox && other university)`. the `university` field is hidden when the checkbox is checked, but it isn't cleared; the client-side validation thus does not always catch when the checkbox is checked but the `other university` question is not filled out. the new rule should be `(university && not checked) || (checked && other university)` and the server probably should have that rule too

**Comment by mhammerly** [comment]
unsetting irrelevant fields isn't happening, it seems.

fill in a university, and save. then edit your application, click the "not listed" checkbox, fill in another university, and save. then edit your application again, and your first university will be showing. if you check the checkbox, the "other university" field will show with its saved value.

**Comment by bogdanpozderca** [comment]
Nice catch, was deleting the field from the hash rather than setting it to nil. Thus never updating the field in the database.

Should be all set
