### ISSUE TITLE
Error messages should be centered

### ISSUE THREAD

**Issue by laurenbretz** [SpartaHack/SpartaHack-Website#171]
It looks sloppy that they have two different alignments

**Comment by mhammerly** [comment]
screenshot?

**Comment by laurenbretz** [comment]
Only happens on some errors, such as email address already exists. Tried to duplicate and got "This site can't be reached" after it timed out...

**Comment by laurenbretz** [comment]
![capture](https://cloud.githubusercontent.com/assets/4753114/20017351/960d392c-a299-11e6-8d2c-2dfe256fa0c9.JPG)
