### ISSUE TITLE
scrollbar doesn't extend to top/bottom of FAQ question section

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack-Website#19]
firefox 49 on linux

looks like it is leaving room for a small lil chevron row thing but no chevron is there

![screenshot](https://cloud.githubusercontent.com/assets/1198161/18822401/6734d71c-837d-11e6-9145-1dc6bbc25395.png)

**Comment by bogdanpozderca** [comment]
JS for the arrows is not there.
