### ISSUE TITLE
unsafe script

### ISSUE THREAD

**Issue by stokesdy** [SpartaHack/SpartaHack-Website#30]
On Chrome Version 53.0.2785.116 m for windows 7 front page is slow and tries to load unsafe script. Allowing the script fixes the speed issue but causes connection to not be private.

![unsafe](https://cloud.githubusercontent.com/assets/8905066/18843380/98f4c30c-83e6-11e6-8a5d-ba16cf7fee05.png)

**Comment by mhammerly** [comment]
same chrome version on windows 7; can confirm the unsafe script issue but do not experience slow speeds.

@stokesdy in what way is the page slow? is the initial load very slow or does the fully-loaded page act sluggish?

**Comment by stokesdy** [comment]
@mhammerly The initial load seems slower than when I enable to script but I could just be seeing things.

**Comment by bogdanpozderca** [comment]
What is the script?

**Comment by stokesdy** [comment]
Yes it seems to be this style sheet http://yui.yahooapis.com/3.18.1/build/cssreset-context/cssreset-context-min.css
