### ISSUE TITLE
Ampersands in names show as &amp; in dropdown - Safari 10.0.1

### ISSUE THREAD

**Issue by SuperUser320** [SpartaHack/SpartaHack-Website#63]
<img width="586" alt="screen shot 2016-10-30 at 4 15 31 pm" src="https://cloud.githubusercontent.com/assets/2801596/19839659/35b1a8d2-9ebc-11e6-8a19-e1a16781cfac.png">

**Comment by memuyskens** [comment]
Chrome has this issue as well
