### ISSUE TITLE
Question text colors alternate between light and dark (in dark mode)

### ISSUE THREAD

**Issue by laurenbretz** [SpartaHack/SpartaHack-Website#71]
Choose lighter color

**Comment by mhammerly** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1198161/19842463/a9a79d86-9eef-11e6-9237-e05f5b5970a6.png)

**Comment by austintruchan** [comment]
Go with the lighter color. I would say lighter color for all text on the dark background.
