### ISSUE TITLE
Icons for handles/links are not always black on gold

### ISSUE THREAD

**Issue by memuyskens** [SpartaHack/SpartaHack-Website#73]

**Comment by mhammerly** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1198161/19842444/77cbcaa8-9eef-11e6-8371-2bcc99f5c183.png)

**Comment by mhammerly** [comment]
@austintruchan in case you have the source for these icons/can make the insides of the white-fill ones transparent

**Comment by austintruchan** [comment]
Just provided bogdan with the new assets
