### ISSUE TITLE
Let's make the travel questions conditional

### ISSUE THREAD

**Issue by laurenbretz** [SpartaHack/SpartaHack-Website#86]
(Change from the spec)

Currently we show two travel questions: which university is closest to you (same list as which do you attend) and are you traveling from outside NA.

To avoid confusion, we might instead show a radio button for "Are you traveling from outside of North America?" "Yes" "No". 
If "Yes", don't display list of universities closest to them.
If "No", ask "Which school will you be traveling from? (choose closest)" and display dropdown.

**Comment by mhammerly** [comment]
also saves us from having to maintain a list of universities in egypt and india B)

**Comment by mhammerly** [comment]
as far as requirements go for validation:

"Which school do you attend" is required OR ("College/University not listed" is checked AND a different university is specified in the freetext that appears) is required

currently the second "fill in your university" question doesn't appear so this condition isn't satisfied

**Comment by mhammerly** [comment]
implemented by @milesjos
