### ISSUE TITLE
backspace doesn't work in the "how many hackathons have you attended" question

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack-Website#99]
if i type "33" i am unable to backspace back to just "3", ff 49 linux

**Comment by bogdanpozderca** [comment]
Thanks for catching that, i have a js check for char codes for 0-9 forgot backspace

**Comment by mhammerly** [comment]
still doesn't work in firefox. if you change this question to a dropdown with choices for 0 through 10+ it is sidestepped. we don't really care about outliers so that limited range is fine

**Comment by mhammerly** [comment]
confirmed fixed by bogdan, switched to keyCode over charCode
